belanjainaja/urls.py
#type:ignore

from django.urls import path

from .views import item, deposit, wallet, withdraw, shop
from . import views

app_name='belanja'

urlpatterns = [
    path("", views.index, name="index"),
    path("init-wallet/", views.init_wallet, name="init-wallet"),
    path("reset/", views.reset, name="reset"),

    path("item/", item.index, name="item.index"),
    path("item/create/", item.create, name="item.create"),
    path("item/<int:item_id>/update/", item.update, name="item.update"),
    path("item/<int:item_id>/delete/", item.delete, name="item.delete"),

    path("deposit/", deposit.index, name="deposit.index"),
    path("deposit/create/", deposit.create, name="deposit.create"),
    path("deposit/<int:deposit_id>/update/", deposit.update, name="deposit.update"),
    path("deposit/<int:deposit_id>/delete/", deposit.delete, name="deposit.delete"),

    path("wallet/", wallet.index, name="wallet.index"),

    path("withdraw/", withdraw.index, name="withdraw.index"),
    path("withdraw/create/", withdraw.create, name="withdraw.create"),
    path("withdraw/<int:withdraw_id>/update/", withdraw.update, name="withdraw.update"),
    path("withdraw/<int:withdraw_id>/delete/", withdraw.delete, name="withdraw.delete"),

    path("shop/", shop.index, name="shop.index"),
    path("shop/create/", shop.create, name="shop.create"),
    path("shop/<int:shop_id>/update/", shop.update, name="shop.update"),
    path("shop/<int:shop_id>/add-item/", shop.add_item, name="shop.add_item"),
    path("shop/<int:shop_id>/verify/", shop.verify, name="shop.verify"),
    path("shop/<int:shop_id>/detail/", shop.detail, name="shop.detail"),
    path("shop/<int:shop_id>/delete-item/", shop.delete_item, name="shop.delete_item"),
]

projects/urls.py
#type:ignore

"""
URL configuration for projects project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('belanjainaja/', include('belanjainaja.urls')),
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
    path('', views.index, name='projects'),

    path('accounts/login/', views.signin, name='signin'),
    path('accounts/logout/', views.signout, name='signout'),
    path('accounts/register/', views.register, name='register'),
]

todolist/urls.py
#type:ignore

from django.urls import path

from . import views

app_name='todos'
urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:todo_id>/", views.detail, name="detail"),
    path("<int:todo_id>/update/", views.update, name="update"),
    path("<int:todo_id>/delete/", views.delete, name="delete"),
    path("<int:todo_id>/update-status", views.update_status, name="update_status"),
    path("recap/", views.recap, name="recap"),
]

belanjainaja/models.py
#type:ignore

from django.db import models

class Item(models.Model):
    name = models.CharField(max_length=50, unique=True)
    price = models.IntegerField()

class Shopping(models.Model):
    purchase_date = models.DateField()
    description = models.CharField(max_length=500)
    total_price = models.BigIntegerField(default=0)
    is_verify = models.BooleanField(default=False)
    items = models.ManyToManyField(Item, through='ShoppingItem')

class ShoppingItem(models.Model):
    shopping = models.ForeignKey(Shopping, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.BigIntegerField()
    unit = models.CharField(max_length=10)
    total_price = models.BigIntegerField()

class Wallet(models.Model):
    income = models.BigIntegerField()
    expenditure = models.BigIntegerField()
    balance = models.BigIntegerField()

class Deposit(models.Model):
    saved_on = models.DateField()
    amount = models.BigIntegerField()
    description = models.CharField(max_length=500, )

class Withdraw(models.Model):
    pulled_on = models.DateField()
    amount = models.BigIntegerField()
    description = models.CharField(max_length=500, )

todolist/models.py
#type:ignore

from django.db import models

class Todo(models.Model):
    title = models.CharField(max_length=500)
    status = models.CharField(max_length=5)

projects/views.py
#type:ignore

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponseNotFound

from belanjainaja.models import *

def index(request):
    return render(request, "projects.html")

def signin(request):

    if request.user.is_authenticated:
        return redirect("belanja:index")

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("belanja:index")
        else:
            messages.add_message(request, messages.ERROR, "Username atau Password salah.")

    return render(request, "signin.html")

def signout(request):

    if request.method == "POST":
        logout(request)
        return redirect("belanja:index")
    
    return HttpResponseNotFound()

def register(request):

    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']

        try:
            user = User.objects.create_user(username, email, password)
            user.save()
            messages.add_message(request, messages.SUCCESS, f'Berhasil registrasi dengan email {email}')
        except Exception as err:
            messages.add_message(request, messages.ERROR, err)

    return render(request, "register.html")

todolist/views.py
#type:ignore

from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import Todo

def index(request):
    latest_todo_list = Todo.objects.all()
    context = {
        "latest_todo_list": latest_todo_list
    }
    return render(request, "todolist/index.html", context=context)

def create(request):
    new_todo = Todo()
    
    new_todo.title = request.POST["title"]
    new_todo.status = 'DO'
    
    new_todo.save()

    return HttpResponseRedirect(reverse("todos:index"))

def update(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)

    if (request.method == "POST"):
        todo.title = request.POST["title"]
        todo.save()
        return HttpResponseRedirect(reverse("todos:index"))

    return render(request, "todolist/update.html", context={"todo": todo})

def delete(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    todo.delete()
    return HttpResponseRedirect(reverse("todos:index"))

def detail(request, todo_id):
    try:
        todo = Todo.objects.get(pk=todo_id)
    except Todo.DoesNotExist:
        raise Http404("Todo does not exist")
    
    return render(request, "todolist/detail.html", {"todo": todo})

def recap(request):
    todos = Todo.objects.all()
    
    return render(request, "todolist/recap.html", {"todos": todos})

def update_status(request, todo_id):
    try:
        todo = Todo.objects.get(pk=todo_id)
    except Todo.DoesNotExist:
        raise Http404("Todo does not exist")
    
    todo.status = request.POST['status']
    todo.save()

    return HttpResponseRedirect(reverse("todos:index"))

belanjainaja/templates/belanjainaja/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Belanja Yuk!</title>

  <link rel="stylesheet" href="{% static 'belanjainaja/style.css' %}">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link
    href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
    rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

  <style>
    body {
      padding: 0;
      margin: 0;
      font-family: 'Roboto';
    }
  </style>
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'belanja:index' %}">BelanjainAja</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav w-100">
          <li class="nav-item">
            <a {% if request.path == "/belanjainaja/item/" %} class="nav-link text-primary" {% endif %}
              class="nav-link" href="{% url 'belanja:item.index' %}">Barang</a>
          </li>
          <li class="nav-item">
            <a {% if request.path == "/belanjainaja/deposit/" %} class="nav-link text-primary" {% endif %}
              class="nav-link" href="{% url 'belanja:deposit.index' %}">Pemasukan</a>
          </li>
          <li class="nav-item">
            <a {% if request.path == "/belanjainaja/withdraw/" %} class="nav-link text-primary" {% endif %}
              class="nav-link" href="{% url 'belanja:withdraw.index' %}">Pengeluaran</a>
          </li>
          <li class="nav-item">
            <a {% if request.path == "/belanjainaja/shop/" %} class="nav-link text-primary" {% endif %} class="nav-link"
              href="{% url 'belanja:shop.index' %}">Belanja</a>
          </li>
          <li class="nav-item dropdown ms-0 ms-sm-auto">
          {% include 'belanjainaja/profile-actions.html' %}
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container py-4">
    {% if messages %}
      {% for message in messages %}
        <div {% if message.tags %} class="alert {{ message.tags }}" {% endif %}>{{ message }}</div>
      {% endfor %}
    {% endif %}
    {% block content %} {% endblock %}
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
    <script>
      console.log('base nih')
    </script>
  {% block extra_script %} {% endblock %}
</body>

</html>

belanjainaja/templates/belanjainaja/deposit/create.html
{% extends 'belanjainaja/base.html' %}

{% block content %}
<div>
  <div class="container">
    <form action="{% url 'belanja:deposit.create' %}" method="post">
      {% csrf_token %}
      <div class="mb-3 row">
        <label for="saved_on" class="col-2 col-form-label">Tanggal Pemasukan</label>
        <div class="col-10">
          <input type="date" class="form-control" name="saved_on" id="saved_on" required />
        </div>
      </div>
      <div class="mb-3 row">
        <label for="amount" class="col-2 col-form-label">Jumlah</label>
        <div class="col-10">
          <input type="text" class="form-control" name="amount" id="amount" placeholder="19000" required />
        </div>
      </div>
      <div class="mb-3 row">
        <label for="description" class="col-2 col-form-label">Keterangan</label>
        <div class="col-10">
          <textarea class="form-control" name="description" id="description"></textarea>
        </div>
      </div>
      <div class="mb-3 row">
        <div class="offset-sm-2 col-sm-10">
          <button type="submit" class="btn btn-sm btn-primary">
            Simpan
          </button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

belanjainaja/templates/belanjainaja/deposit/index.html
{% extends "belanjainaja/base.html" %}

{% block content %}
<div class="d-flex justify-content-between mb-3">
  <div>
    <h6 class="mb-0">Data Pemasukan</h6>
    <p class="text-secondary mt-0 fst-italic fw-light" style="font-size: 13px;">Catatan data keuangan masuk.</p>
  </div>
  <a href="{% url 'belanja:deposit.create' %}">+ Tambah Pemasukan</a>
</div>
{% if not latest_deposit_list %}
<p>data not available.</p>
{% else %}
<div class="table-responsive">
  <table class="table table-sm align-middle">
    <thead class="bg-secondary text-white">
      <tr>
        <th>No.</th>
        <th>Tanggal Pemasukan</th>
        <th>Jumlah</th>
        <th>Keterangan</th>
        <th>Aksi</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      {% for deposit in latest_deposit_list %}
      <tr>
        <td scope="row">{{forloop.counter}}</td>
        <td>{{deposit.saved_on}}</td>
        <td>{{deposit.amount}}</td>
        <td>{{deposit.description}}</td>
        <td class="d-flex justify-center align-items-center">
          <a href="{% url 'belanja:deposit.update' deposit.id %}" class="btn btn-sm btn-info me-1">Ubah</a>
          <form action="{% url 'belanja:deposit.delete' deposit.id %}" method="POST" class="mb-0">
            {% csrf_token %}
            <button type="submit" class="btn btn-sm btn-danger">Hapus</button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
    <tfoot>

    </tfoot>
  </table>
</div>
{% endif %}
{% endblock %}

belanjainaja/templates/belanjainaja/deposit/update.html
{% extends 'belanjainaja/base.html' %}

{% block content %}
<div>
  <div class="container">
    <form action="{% url 'belanja:deposit.update' deposit.id %}" method="post">
      {% csrf_token %}
      <div class="mb-3 row">
        <label for="saved_on" class="col-2 col-form-label">Tanggal Pemasukan</label>
        <div class="col-10">
          <input type="date" class="form-control" name="saved_on" id="saved_on" value="{{deposit.saved_on}}" required />
        </div>
      </div>
      <div class="mb-3 row">
        <label for="amount" class="col-2 col-form-label">Jumlah</label>
        <div class="col-10">
          <input type="text" class="form-control" name="amount" id="amount" value="{{deposit.amount}}" placeholder="19000" required />
        </div>
      </div>
      <div class="mb-3 row">
        <label for="description" class="col-2 col-form-label">Keterangan</label>
        <div class="col-10">
          <textarea class="form-control" name="description" id="description">{{deposit.description}}</textarea>
        </div>
      </div>
      <div class="mb-3 row">
        <div class="offset-sm-2 col-sm-10">
          <button type="submit" class="btn btn-sm btn-primary">
            Simpan
          </button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

belanjainaja/templates/belanjainaja/index.html
{% extends 'belanjainaja/base.html' %}

{% block content %}
  <p><a href="{% url 'projects' %}"><i class="bi bi-arrow-left"></i> Projects</a></p>
  <h6 class="text-dark">Selamat datang di aplikasi BelanjainAja</h6>
  <p style="font-size: 14px;" class="text-secondary fst-italic">Menjadi lebih hemat dengan mengatur belanja bulanan anda.</p>
  <p>Silakan <a href="{% url 'belanja:reset' %}">Reset</a> data sebelum mencoba aplikasi !</p>
{% endblock %}

belanjainaja/templates/belanjainaja/item/create.html
{% extends 'belanjainaja/base.html' %}

{% block content %}
<div>
  <div class="container">
    <form action="{% url 'belanja:item.create' %}" method="post">
      {% csrf_token %}
      <div class="mb-3 row">
        <label for="name" class="col-2 col-form-label">Nama Barang</label>
        <div class="col-10">
          <input type="text" class="form-control" name="name" id="name" placeholder="Minyak Goreng" required/>
        </div>
      </div>
      <div class="mb-3 row">
        <label for="price" class="col-2 col-form-label">Harga Barang</label>
        <div class="col-10">
          <input type="text" class="form-control" name="price" id="price" placeholder="19000" required/>
        </div>
      </div>
      <div class="mb-3 row">
        <div class="offset-sm-2 col-sm-10">
          <button type="submit" class="btn btn-sm btn-primary">
            Simpan
          </button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

belanjainaja/templates/belanjainaja/item/index.html
{% extends "belanjainaja/base.html" %}

{% block content %}
<div class="d-flex justify-content-between mb-3">
  <div>
    <h6 class="mb-0">Data Barang</h6>
    <p class="text-secondary mt-0 fst-italic fw-light" style="font-size: 13px;">Data barang yang akan muncul saat
      membuat catatan belanja.</p>
  </div>
  <a href="{% url 'belanja:item.create' %}">+ Tambah Barang</a>
</div>
{% if not latest_item_list %}
<p>data not available.</p>
{% else %}
<div class="table-responsive">
  <table class="table table-sm align-middle">
    <thead class="bg-secondary text-white">
      <tr>
        <th>No.</th>
        <th>Nama Barang</th>
        <th>Harga Barang</th>
        <th>Aksi</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
      {% for item in latest_item_list %}
      <tr>
        <td scope="row">{{forloop.counter}}</td>
        <td>{{item.name}}</td>
        <td>{{item.price}}</td>
        <td class="d-flex justify-center align-items-center">
          <a href="{% url 'belanja:item.update' item.id %}" class="btn btn-sm btn-info me-1">Ubah</a>
          <form action="{% url 'belanja:item.delete' item.id %}" method="POST" class="mb-0">
            {% csrf_token %}
            <button type="submit" class="btn btn-sm btn-danger">Hapus</button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endif %}
{% endblock %}

belanjainaja/templates/belanjainaja/item/update.html
{% extends 'belanjainaja/base.html' %}

{% block content %}
<div>
  <div class="container">
    <form action="{% url 'belanja:item.update' item.id %}" method="post">
      {% csrf_token %}
      <div class="mb-3 row">
        <label for="name" class="col-2 col-form-label">Nama Barang</label>
        <div class="col-10">
          <input type="text" class="form-control" name="name" id="name" value="{{item.name}}" placeholder="Minyak Goreng" required/>
        </div>
      </div>
      <div class="mb-3 row">
        <label for="price" class="col-2 col-form-label">Harga Barang</label>
        <div class="col-10">
          <input type="text" class="form-control" name="price" id="price" value="{{item.price}}" placeholder="19000" required/>
        </div>
      </div>
      <div class="mb-3 row">
        <div class="offset-sm-2 col-sm-10">
          <button type="submit" class="btn btn-sm btn-primary">
            Simpan
          </button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

belanjainaja/templates/belanjainaja/profile-actions.html
<a class="nav-link dropdown-toggle" id="profileDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
  {{request.user.username}}
</a>
<ul class="dropdown-menu dropdown-menu-light shadow-sm" aria-labelledby="profileDropdown">
  <li><a class="dropdown-item" href="{% url 'belanja:wallet.index' %}"><i class="bi bi-currency-dollar"></i> Cek Saldo</a></li>
  <li>
    <form action="{% url 'signout' %}" method="post">
      {% csrf_token %}
      <button class="dropdown-item btn btn-sm btn-danger w-100 text-danger" type="submit"><i class="bi bi-power"></i> Sign out</button>
    </form>
  </li>
</ul>

belanjainaja/templates/belanjainaja/shop/add-item.html
{% extends 'belanjainaja/base.html' %}

{% block content %}
<div>
  <div class="container">
    <div class="row g-5">
      <div class="col-6">
        <div class="card text-secondary shadow-sm">
          <div class="card-body">
            <h4 class="card-title">{{shop.description}}</h4>
            <p class="card-text">{{shop.purchase_date}}</p>
            <ul>
              {% for shop_item in shopping_item %}
              <li>{{shop_item.item.name}} | @Rp{{shop_item.price}} | {{ shop_item.quantity }} | {{ shop_item.unit }} | Rp{{ shop_item.total_price }}
                <form action="{% url 'belanja:shop.delete_item' shop.id %}" method="post">
                  {% csrf_token %}
                  <input type="number" value="{{shop_item.item.id}}" name="shop_item_id" hidden>
                  <input type="submit" value="Delete"/>
                </form>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>

      </div>
      <div class="col-6">
        <form action="{% url 'belanja:shop.add_item' shop.id %}" method="post">
          {% csrf_token %}
          <div class="mb-3 row">
            <label for="item_id" class="col-2 col-form-label">Barang</label>
            <div class="col-10">
              <select class="form-select form-select-sm" id="item_id" name="item_id">
                <option value="" disabled selected="selected">-Pilih Barang-</option>
                {% for item in latest_item_list %}
                <option value="{{item.id}}`{{item.price}}">{{item.name}}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="mb-3 row">
            <label for="price" class="col-2 col-form-label">Harga</label>
            <div class="col-10">
              <input type="text" disabled class="form-control" name="price" id="price" placeholder="15000" required />
            </div>
          </div>
          <div class="mb-3 row">
            <label for="quantity" class="col-2 col-form-label">Jumlah</label>
            <div class="col-10">
              <input type="text" class="form-control" name="quantity" id="quantity" placeholder="5" required />
            </div>
          </div>
          <div class="mb-3 row">
            <label for="unit" class="col-2 col-form-label">Satuan</label>
            <div class="col-10">
              <input type="text" class="form-control" name="unit" id="unit" placeholder="PCS" required />
            </div>
          </div>
          <div class="mb-3 row">
            <div class="offset-sm-2 col-sm-10">
              <button type="submit" class="btn btn-sm btn-primary">
                Simpan
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
{{ super }}
<script>
  const params = new URLSearchParams(location.search)
  const itemId = document.getElementById('item_id')
  const price = document.getElementById('price')

  itemId.addEventListener('change', (e) => {
    const itemElementValue = e.target.value
    const splitItemIdAndPrice = itemElementValue.split('`')
    const priceItem = splitItemIdAndPrice[1]
    price.removeAttribute('disabled')
    price.value = priceItem
  })

  const editItemData = (e) => {
    params.set('item_id', e.getAttribute('data-id'))
    location.search = params
  }
</script>
{% endblock %}

belanjainaja/templates/belanjainaja/shop/detail.html
{% extends 'belanjainaja/base.html' %}

{% block content %}
<div>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <a href="{% url 'belanja:shop.index' %}">Kembali</a>
        <div class="card text-secondary shadow-sm">
          <div class="card-body">
            <h4 class="card-title">{{shop.description}}</h4>
            <p class="card-text">{{shop.purchase_date}}</p>
            <ul>
              {% for shop in shopping_item %}
              <li>{{shop.item.name}} | @Rp{{shop.price}} | {{ shop.quantity }} | {{ shop.unit }} | Rp{{ shop.total_price }} </li>
              {% endfor %}
            </ul>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
{% endblock %}

belanjainaja/templates/belanjainaja/shop/update.html
{% extends 'belanjainaja/base.html' %}

{% block content %}
<div>
  <div class="container">
    <form action="{% url 'belanja:shop.update' shop.id %}" method="post">
      {% csrf_token %}
      <div class="mb-3 row">
        <label for="saved_on" class="col-2 col-form-label">Tanggal Pemasukan</label>
        <div class="col-10">
          <input type="date" class="form-control" name="saved_on" id="saved_on" value="{{shop.saved_on}}" required />
        </div>
      </div>
      <div class="mb-3 row">
        <label for="amount" class="col-2 col-form-label">Jumlah</label>
        <div class="col-10">
          <input type="text" class="form-control" name="amount" id="amount" value="{{shop.amount}}" placeholder="19000" required />
        </div>
      </div>
      <div class="mb-3 row">
        <label for="description" class="col-2 col-form-label">Keterangan</label>
        <div class="col-10">
          <textarea class="form-control" name="description" id="description">{{shop.description}}</textarea>
        </div>
      </div>
      <div class="mb-3 row">
        <div class="offset-sm-2 col-sm-10">
          <button type="submit" class="btn btn-sm btn-primary">
            Simpan
          </button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

todolist/templates/todolist/detail.html
{% extends 'todolist/base.html' %}

{% block content %}
<a href="{% url 'todos:index' %}">Back</a>
<h1>{{todo.title}}</h1>
{% endblock %}

todolist/templates/todolist/index.html
{% extends 'todolist/base.html' %}

{% block content %}
<div>
    <form action="{% url 'todos:create' %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>
                <h1>Form Add Todo</h1>
            </legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <input class="form-input" type="text" name="title" required />
            <button type="submit" class="btn btn-primary">Add todo</button>
        </fieldset>
    </form>

    {% if latest_todo_list %}
    <ul>
        {% for todo in latest_todo_list %}
        <li>
            <a href="/todolist/{{ todo.id }}/">{{ todo.title }}</a> | <a style="color: salmon;"
                href="{% url 'todos:delete' todo.id %}">Delete</a> | <a style="color: green;"
                href="{% url 'todos:update' todo.id %}">Update</a>
        </li>
        <form action="{% url 'todos:update_status' todo.id %}" method="post">
            {% csrf_token %}
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

            <div style="display: flex;">
                <div>
                    <input type="radio" name="status" id="{{todo.id}}do" value='DO' {% if todo.status == "DO" %}
                        checked="checked" {% endif %}>
                    <label for="{{todo.id}}do">Do</label>
                </div>

                <div>
                    <input type="radio" name="status" id="{{todo.id}}doing" value='DOING' {% if todo.status == "DOING" %}
                        checked="checked" {% endif %}>
                    <label for="{{todo.id}}doing">Doing</label>
                </div>
                <div>
                    <input type="radio" name="status" id="{{todo.id}}done" value='DONE' {% if todo.status == "DONE" %}
                        checked="checked" {% endif %}>
                    <label for="{{todo.id}}done">Done</label><br>
                </div>
                <button type="submit" style="margin-left: 2px;">Update status</button>
            </div>
        </form>
        {% endfor %}
        <div><a href="{% url 'todos:recap' %}">Recap</a></div>
    </ul>

    {% else %}
    <p>No todos are available.</p>
    {% endif %}
</div>
{% endblock %}

todolist/templates/todolist/update.html
{% extends 'todolist/base.html' %}

{% block content %}
<div style="display: flex;">
    <form action="{% url 'todos:update' todo.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>
                <h1>Form Update Todo</h1>
            </legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <input class="form-input" type="text" name="title" value="{{todo.title}}" required />
            <button type="submit" class="btn btn-warning">Update todo</button>
        </fieldset>
    </form>
</div>
{% endblock %}